include: package:flutter_lints/flutter.yaml # Includes recommended rules.

linter:
  rules:
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
    avoid_multiple_declarations_per_line: true
    avoid_unnecessary_containers: true
    cascade_invocations: true
