name: faltometro_ufrgs
description: A mobile app for UFRGS students to control their frequency in classes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  phosphor_flutter: ^2.0.0
  path_provider: ^2.1.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
