name: faltometro_ufrgs
description: A mobile app for UFRGS students to control their class attendance.
publish_to: 'none'
version: 1.4.0+6
homepage: https://github.com/bernardolansing/faltometro_ufrgs
issue_tracker: https://github.com/bernardolansing/faltometro_ufrgs/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '3.35.1'

dependencies:
  calendar_date_picker2: ^1.1.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  phosphor_flutter: 2.0.0
  timezone: ^0.9.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/white-logo.png
    - assets/front.png
    - assets/white-mark.png
