name: faltometro_ufrgs
description: A mobile app for UFRGS students to control their class attendance.
publish_to: 'none'
version: 1.1.0
homepage: https://github.com/bernardolansing/faltometro_ufrgs

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '3.24.5'

dependencies:
  flutter:
    sdk: flutter
  phosphor_flutter: 2.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.1.14
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/white-logo.png
    - assets/front.png
