-- Script for creating the tables in a new database.

CREATE TABLE courses (
    code CHAR(8) PRIMARY KEY,
    title TEXT NOT NULL,
    
    CHECK (code ~ '^[A-Z]{3}\d{5}$')
);

CREATE TYPE weekday AS ENUM ('mon', 'tue', 'wed', 'thu', 'fri', 'sat');

CREATE TABLE course_options (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    course_code CHAR(8) REFERENCES courses (code),
    option_name VARCHAR(2) NOT NULL,

    CHECK (option_name = UPPER(option_name))
);

CREATE TABLE course_options_class_sessions (
    course_option INT REFERENCES course_options,
    starting_time CHAR(5) NOT NULL,
    weekday weekday NOT NULL,
    periods SMALLINT NOT NULL,
    location TEXT,

    CHECK (periods > 0),
    CHECK (starting_time ~ '^(?:[01]?[0-9]|2[0-3]):[0-5][0-9]$')
);
