-- Script for creating the tables in a new database.

CREATE TABLE courses (
    code CHAR(8) PRIMARY KEY,
    title TEXT NOT NULL,
    
    CHECK (code ~ '^[A-Z]{3}(\d{5}|\d{2}[A-Z]{1}\d{2})$')
);

CREATE TABLE course_options (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    course_code CHAR(8) REFERENCES courses ON DELETE CASCADE,
    option_name VARCHAR(2) NOT NULL,

    CHECK (option_name = UPPER(option_name))
);

CREATE TABLE course_options_class_sessions (
    id INT GENERATED ALWAYS AS IDENTITY,
    course_option_id INT REFERENCES course_options ON DELETE CASCADE,
    starting_time VARCHAR(5) NOT NULL,
    weekday weekday NOT NULL,
    periods SMALLINT NOT NULL,
    location TEXT,

    CHECK (periods > 0),
    CHECK (starting_time ~ '^[A-Z0-9]{8}$')
);
