-- Script for creating the tables in a new database.

CREATE TABLE courses (
    code CHAR(8) PRIMARY KEY,
    title TEXT NOT NULL,
    
    CHECK (code ~ '^[A-Z0-9]{8}$')
);

CREATE TABLE course_options (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    course_code CHAR(8) REFERENCES courses ON DELETE CASCADE,
    option_name VARCHAR(2) NOT NULL,

    CHECK (option_name = UPPER(option_name))
);

CREATE TABLE course_options_class_sessions (
    id INT GENERATED ALWAYS AS IDENTITY,
    course_option_id INT REFERENCES course_options ON DELETE CASCADE,
    starting_time VARCHAR(5) NOT NULL,
    weekday CHAR NOT NULL,
    periods SMALLINT NOT NULL,
    location TEXT,

    CHECK (periods > 0),
    CHECK (starting_time ~ '^(?:[01]?[0-9]|2[0-3]):[0-5][0-9]$')
);

-- This table is meant for checking whether front end caches are updated or not. Every time a scraped table is
-- repopulated, a new generation number is assigned.
CREATE TABLE generations (
    id TEXT PRIMARY KEY,
    generation_number INT NOT NULL
);
INSERT INTO generations VALUES ('courses', random(0, 2147483647));
INSERT INTO generations VALUES ('course_options', random(0, 2147483647));
