# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09

# SAM template transform:
Transform:
  - AWS::Serverless-2016-10-31

Resources:

  UpdateCourses:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda Function that scraps and updates the list of courses.
      CodeUri: ./Scraper/
      Handler: Scraper::Scraper.UpdateCourses::Handler
      PackageType: Zip
      Runtime: dotnet10
      MemorySize: 512
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
