name: faltometro_ufrgs
description: A mobile app for UFRGS students to control their class attendance.
publish_to: 'none'
version: 1.5.0+7
homepage: https://github.com/bernardolansing/faltometro_ufrgs
issue_tracker: https://github.com/bernardolansing/faltometro_ufrgs/issues

environment:
  sdk: '>=3.12.2 <4.0.0'
  flutter: '3.44.5'

dependencies:
  calendar_date_picker2: ^1.1.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  # phosphor_flutter repository was abandoned by its owner, so in order to fix it for Flutter 3.44+
  # we have to rely in this PR ref.
  phosphor_flutter:
    git:
      url: https://github.com/phosphor-icons/flutter
      ref: 514f0a883571c4453dbd6ee3041d1dcba4fb8fc7
  timezone: ^0.9.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/white-logo.png
    - assets/front.png
    - assets/white-mark.png
